# Generated by Django 5.2 on 2025-04-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0002_alter_user_options_user_created_at_user_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
