# Generated by Django 5.2 on 2025-05-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hades', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
