# Generated by Django 5.2 on 2025-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilitia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cedula'),
        ),
    ]
