# Generated by Django 5.2 on 2025-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilitia', '0002_alter_client_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='days_to_pay',
            field=models.IntegerField(default=0),
        ),
    ]
