# Generated by Django 5.2 on 2025-05-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilitia', '0004_sale_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
