# Generated by Django 5.2 on 2025-05-02 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilitia', '0006_alter_sale_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
