# Generated by Django 5.2 on 2025-04-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artemisa', '0004_alter_pricehistory_purchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='discount',
            new_name='discount_total',
        ),
    ]
