# Generated by Django 5.2 on 2025-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemisa', '0005_rename_discount_purchase_discount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero de factura'),
        ),
    ]
