# Generated by Django 5.2 on 2025-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemisa', '0006_alter_purchase_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmeasure',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kilogramo'), ('g', 'Gramo'), ('qq', 'Quintal'), ('T', 'Tonelada'), ('Lt', 'Litro'), ('mL', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('Un', 'Unidad'), ('Doc', 'Docena'), ('Gl', 'Galón'), ('Paq', 'Paquete'), ('Bul', 'Bulto'), ('Caja', 'Caja'), ('saco', 'Saco'), ('Bot', 'Botella'), ('bidon', 'Bidón')], max_length=50),
        ),
    ]
