# Generated by Django 5.2 on 2025-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemisa', '0007_alter_unitmeasure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de compra'),
        ),
    ]
