# Generated by Django 5.2 on 2025-04-22 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemisa', '0008_product_purchase_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='provider',
            name='dni',
            field=models.CharField(max_length=50, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kilogramo'), ('g', 'Gramo'), ('T', 'Tonelada'), ('Lt', 'Litro'), ('mL', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro'), ('mm', 'Milímetro'), ('Un', 'Unidad'), ('Doc', 'Docena'), ('Gl', 'Galón'), ('Paq', 'Paquete'), ('Bul', 'Bulto'), ('Caja', 'Caja'), ('saco', 'Saco'), ('Bot', 'Botella'), ('bidon', 'Bidón'), ('qq', 'Quintal')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProductPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artemisa.unitmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artemisa.productpresentation', verbose_name='Presentación'),
        ),
    ]
