# Generated by Django 5.2 on 2025-04-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemisa', '0010_remove_product_presentation_product_unit_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='days_to_pay',
            field=models.IntegerField(default=0, verbose_name='Días para pagar'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type_payment',
            field=models.CharField(choices=[('CREDIT', 'Crédito'), ('CASH', 'Contado')], default='CASH', max_length=10),
        ),
    ]
