# Generated by Django 5.2 on 2025-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemisa', '0011_purchase_days_to_pay_alter_purchase_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='type_payment',
            field=models.CharField(choices=[('CREDIT', 'Crédito'), ('CASH', 'Contado')], default='CREDIT', max_length=10),
        ),
        migrations.DeleteModel(
            name='PurchasePayment',
        ),
    ]
