# Generated by Django 5.2 on 2025-04-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasepayment',
            name='method',
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='days_to_expiration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
