# Generated by Django 5.2 on 2025-05-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0004_cashclosing_detcashclosingsale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detcashclosingsalepayment',
            name='cashclosing',
        ),
        migrations.RemoveField(
            model_name='detcashclosingsalepayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='detcashclosingsalepayment',
            name='sale_payment',
        ),
        migrations.RemoveField(
            model_name='detcashclosingsalepayment',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='DetCashClosingSale',
        ),
        migrations.DeleteModel(
            name='DetCashClosingSalePayment',
        ),
    ]
