# Generated by Django 5.2 on 2025-05-02 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0005_remove_detcashclosingsalepayment_cashclosing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
